### ISSUE TITLE
InvalidStatusCode

### ISSUE THREAD

**Issue by JSRossiter** [slazarov/python-bittrex-websocket-aio#6]
I'm getting the following error intermittently while running ~35 connections to subscribe_to_exchange_deltas

```
Exception in thread SocketConnection:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bittrex_websocket/websocket_client.py", line 76, in _connection_handler
    self.connection.conn.start()
  File "/usr/local/lib/python3.6/dist-packages/signalr_aio/_connection.py", line 36, in start
    self.__transport.start()
  File "/usr/local/lib/python3.6/dist-packages/signalr_aio/transports/_transport.py", line 47, in start
    self.ws_loop.run_until_complete(self.socket(self.ws_loop))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/signalr_aio/transports/_transport.py", line 59, in socket
    loop=loop) as self.ws:
  File "/usr/local/lib/python3.6/dist-packages/websockets/client.py", line 386, in __aenter__
    return (yield from self)
  File "/usr/local/lib/python3.6/dist-packages/websockets/client.py", line 400, in __await__
    extra_headers=protocol.extra_headers,
  File "/usr/local/lib/python3.6/dist-packages/websockets/client.py", line 263, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 524
```

**Comment by slazarov** [comment]
Bittrex might have enabled cloudflare again, install cfscrape and it’s dependencies(nodejs). The package will pick it up immediately.

**Comment by JSRossiter** [comment]
I haven't seen the 524 again so that seems to have solved that, thanks, but I did just get this one:
```
Exception in thread SocketConnection:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bittrex_websocket/websocket_client.py", line 76, in _connection_handler
    self.connection.conn.start()
  File "/usr/local/lib/python3.6/dist-packages/signalr_aio/_connection.py", line 36, in start
    self.__transport.start()
  File "/usr/local/lib/python3.6/dist-packages/signalr_aio/transports/_transport.py", line 47, in start
    self.ws_loop.run_until_complete(self.socket(self.ws_loop))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/signalr_aio/transports/_transport.py", line 59, in socket
    loop=loop) as self.ws:
  File "/usr/local/lib/python3.6/dist-packages/websockets/client.py", line 386, in __aenter__
    return (yield from self)
  File "/usr/local/lib/python3.6/dist-packages/websockets/client.py", line 400, in __await__
    extra_headers=protocol.extra_headers,
  File "/usr/local/lib/python3.6/dist-packages/websockets/client.py", line 263, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 503
```

and I've also had a couple of these, again just while running bunch of connections:
```
Exception in thread SocketConnection:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bittrex_websocket/websocket_client.py", line 76, in _connection_handler
    self.connection.conn.start()
  File "/usr/local/lib/python3.6/dist-packages/signalr_aio/_connection.py", line 36, in start
    self.__transport.start()
  File "/usr/local/lib/python3.6/dist-packages/signalr_aio/transports/_transport.py", line 45, in start
    self._ws_params = WebSocketParameters(self._connection)
  File "/usr/local/lib/python3.6/dist-packages/signalr_aio/transports/_parameters.py", line 21, in __init__
    self._negotiate()
  File "/usr/local/lib/python3.6/dist-packages/signalr_aio/transports/_parameters.py", line 51, in _negotiate
    self.socket_conf = request.json()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I haven't really investigated either of these so appreciate any help

**Comment by JSRossiter** [comment]
I also just received another 524, maybe I need to limit the connection attempts or refactor so I use a single connection

**Comment by slazarov** [comment]
Hi, it’s not clear if you installed cfscrape as I said or if you are using any replacements for the json package. It’s highly recommending to provide a list of your packages; isolate your code in a venv in order to avoid package conflicts; and finally to describe your issue with details such as runtime.

What endpoint are you connecting to?

**Comment by slazarov** [comment]
I also see that you are running comlexjson which might be causing your second issue.

**Comment by JSRossiter** [comment]
Yeah I did install cfscrape, I'm not using a venv but this code is the only thing running on a VPS (Ubuntu 16.04). I'm not deliberately using any other json packages, this is my return from pip list:
```
aiodns                1.1.1
aiohttp               3.1.3
asn1crypto            0.24.0
async-timeout         2.0.1
attrs                 17.4.0
autobahn              18.4.1
Automat               0.6.0
bittrex-websocket-aio 0.0.0.2.5
btfxwss               1.1.16
cchardet              2.1.1
ccxt                  1.13.51
certifi               2018.4.16
cffi                  1.11.5
cfscrape              1.9.5
chardet               3.0.4
command-not-found     0.3
constantly            15.1.0
cryptography          2.2.2
dateparser            0.7.0
hitbtc                1.0.4                  /home/bot4/src/hitbtc
hyperlink             18.0.0
idna                  2.6
idna-ssl              1.0.1
incremental           17.5.0
language-selector     0.1
multidict             4.2.0
pip                   10.0.1
psycopg2              2.7.4
psycopg2-binary       2.7.4
pyasn1                0.4.2
pyasn1-modules        0.2.1
pycares               2.3.0
pycparser             2.18
pycurl                7.43.0
pygobject             3.20.0
pyOpenSSL             17.5.0
python-apt            1.1.0b1+ubuntu0.16.4.1
python-binance        0.6.9
python-bittrex        0.3.0
python-dateutil       2.7.2
python-debian         0.1.27
python-systemd        231
pytz                  2018.4
PyYAML                3.12
redis                 2.10.6
regex                 2018.2.21
requests              2.18.4
service-identity      17.0.0
setuptools            39.1.0
signalr-client-aio    0.0.1.6.2
six                   1.10.0
ssh-import-id         5.5
Twisted               17.9.0
txaio                 2.10.0
tzlocal               1.5.1
ufw                   0.35
unattended-upgrades   0.1
urllib3               1.22
websocket-client      0.47.0
websockets            4.0.1
wheel                 0.31.0
yarl                  1.1.0
zope.interface        4.5.0
```

**Comment by slazarov** [comment]
Hi, the errors are coming from Bittrex:

> websockets.exceptions.InvalidStatusCode: Status code not 101: 503

refers to `The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state`.

while
> websockets.exceptions.InvalidStatusCode: Status code not 101: 524

refers to `Cloudflare was able to complete a TCP connection to the origin server, but did not receive a timely HTTP response.`

Reference: [list of HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

**I will add the exceptions in the reconnection procedure.**

Finally, I suggest running the socket in a venv for the reasons stated in my previous posts. Also make sure you have installed node.js

**Comment by JSRossiter** [comment]
Thanks for adding those, that has definitely helped. 

I am still getting the JSON error though, I think it's just another problem with bittrex but it should probably trigger a reconnect. The complexjson thing is just a method name in the requests library.

**Comment by slazarov** [comment]
How long before it occurs?

**Comment by JSRossiter** [comment]
I think it happens during connection or reconnection so sometimes immediately sometimes longer. It’s probably <1% of the time since I’m starting 40 connections at once and doesn’t always happen.

**Comment by slazarov** [comment]
What does `node -v` in the cli return?

Are you starting 40 new instances or subscribing to 40 tickers from one instance?

**Comment by JSRossiter** [comment]
Node 10.0.0

40 separate instances, changing that is on my todo list but I think it just magnifies this problem rather than causes

**Comment by slazarov** [comment]
I have subscribed to all tickers in a single instance and the connection was perfect. Making 40 connections is surely causing some sort of throttling. If you want to spread the subs into more instances, try doing it in the range of 10/20 tickers per instance.
  

  
  

  
  
>

**Comment by JSRossiter** [comment]
Refactoring has stopped this error from occurring for the time being so I'll close this, thanks again for your help.

**Comment by slazarov** [comment]
Great to hear it @JSRossiter. If you would like you can share what you did, I would like to create a section for best practices.

**Comment by JSRossiter** [comment]
I just made this class to sort the order book updates and then I can pull from the queues. I've been getting non-consecutive update IDs pretty regularly and also a couple of times I've just stopped getting updates for all of them but it's workable.
```import queue
from bittrex_websocket.websocket_client import BittrexSocket


class BittrexSocketManager(BittrexSocket):
    def __init__(self):
        super().__init__()
        self.private_q = queue.Queue(100)
        self.default_public_q = queue.Queue(100)
        self.market_queues = {}

    async def on_public(self, msg):
        market = msg.get('M', None)
        if market is not None:
            self.market_queues.setdefault(market, queue.Queue(100)).put(msg)
        else:
            self.default_public_q.put(msg)

    async def on_private(self, msg):
        self.private_q.put(msg)
```

**Comment by slazarov** [comment]
There is a known bug on Bittrex’s side, updates for arbitrary tickers stop streaming even though the connection is open and you are receiving data for other tickers.
